name: Python Scheduled Script

on:
  schedule:
  - cron: "1 12,9 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "US/Eastern"
          
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.
        
      - name: Setup Python Verions
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"
          
      - name: Install Python Dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
          
      - name: Execute Python Script
        run: python main.py
        
      - name: Commit Files
        run: |
          git config --local user.name Peterstangolis
          git config --local user.email "pstangolis@gmail.com"
          git add -A
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
          
      - name: Push changes
        uses: add-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
 
